src/App.css, src/components/BottomSheet/ReviewWrite/ReviewEmoji.tsx, src/components/BottomSheet/ReviewWrite/ReviewInput.tsx, src/components/BottomSheet/ReviewWrite/ReviewRatio.tsx, src/components/BottomSheet/ReviewWrite/ReviewTag.tsx, src/components/BottomSheet/ReviewWrite/ReviewTagList.tsx, src/components/BottomSheet/ReviewWrite/ReviewWrite.tsx
#16 
<br><br>
App.css의 tailwindcss 컬러코드가 적용이 되지 않는 문제가 있어 해당 파일을 수정했습니다. 
필요한 컬러코드를 추가하고 ReviewWrite 폴더의 컴포넌트 색상을 컬러코드로 변경하였습니다.
<br><br>
다음처럼 App.css의 내용을 변경하였습니다.
[전]
[후]
<br><br>
<br><br>
[tailwindcss color](https://tailwindcss.com/docs/colors)
=> Refactor/#16 색상 직접명시에서 컬러코드로 변환

src/components/BottomSheet/BottomSheet.tsx, src/components/BottomSheet/Category/CategoryButton.tsx, src/components/BottomSheet/Category/MapChip.tsx, src/components/BottomSheet/Category/MapChipList.tsx, src/components/BottomSheet/ContentTitle.tsx, src/components/BottomSheet/Preview/PreviewContent.tsx, src/components/BottomSheet/ReviewRange.tsx, src/components/BottomSheet/ReviewWrite/ReviewEmoji.tsx, src/components/BottomSheet/SolmarkChip.tsx, src/components/BottomSheet/Tag.tsx
#21 
<br><br>
바뀐 컬러 코드로 수정
솔마크칩 클릭할 때는 navigate 안되도록 수정
카테고리 버튼 아이콘 가운데 정렬
MapChip 수정된 디자인 반영
<br><br>
<br><br>
<br><br>
=> Refactor/#21 디자인 수정

src/components/BottomSheet/BottomSheet.tsx, src/components/BottomSheet/Category/MapChip.tsx, src/components/BottomSheet/Preview/PreviewContentList.tsx, src/components/BottomSheet/Tag.tsx, src/store/placeStore.ts
#23 
<br><br>
카테고리 선택&필터링 구현
카테고리 선택을 위한 zustand placeStore 추가
<br><br>
<br><br>
(피그마에 한번에 적혀있는 컬러 코드들이랑 피그마의 실제 디자인 색상과 차이가 있어서 컬러코드는 나중에 다시 수정해야할 것 같아요)
<br><br>
=> Feat/#23 카테고리 선택&필터링 구현

.gitignore, index.html, package-lock.json, package.json, src/pages/MapSheet.tsx
#26 
<br><br>
- 네이버 지도 api를 연결한 MapSheet 컴포넌트를 구현했습니다. 
- 초기 지도 로딩할 때 현재 위치로 지도 중심을 설정하도록 했으며, 현재 위치를 가져오지 못하면 서울 시청을 기준으로 하도록 했습니다. 
- navigator.geolocation.getCurrentPosition로 현재 위치 값을 가져왔습니다.
- 우선 places 데이터로 마커를 표시하도록 했습니다. (해당 값은 지도 첫 로딩시 서버에서 받아오는 값으로 생각하여, 지도 로딩시 현재 위치와 관계없이 지도에 표시되도록 했습니다.) 
- 마커를 클릭하면 해당 마커가 화면의 중앙에 오도록 구현했습니다. 
- 화면 중앙 우측의 임시 버튼으로 현재 위치로 지도를 이동하도록 구현했습니다. 
- 화면 중앙 좌측의 임시 버튼으로 지도에 표시된 마커가 모두 화면에 나오도록 지도를 이동하는 기능을 구현했습니다. 
이때 panToBounds 함수(표시된 마커들을 화면의 경계로 맞추는 함수)의 margin 값을 (30 30 200 30)로 설정했습니다. 200은  bottom인데 바텀시트가 중간 정도까지 올라온 상태에서 화면 중앙을 맞추기위해 숫자를 크게 설정했습니다. 추후 세밀한 값으로 수정 필요할 것 같습니다.
<br><br>
위 사진은, 위치 허용이 안되었을 때 첫 로딩된 지도 중심 및 '현재 위치로 버튼' 위치입니다.
위 사진은, 위치 허용이 되었을 때 첫 로딩된 지도 중심 및 '현재 위치로 버튼' 위치입니다. (사용자 위치에 따라 다름) 
위 사진은, 두 번째 사진에서 화면을 그대로 축소했을 때 마커가 찍혀있는 것을 …
=> Feat/#26 마커 기반 지도 중심 변경 구현 

src/components/BottomSheet/BottomSheet.tsx, src/components/BottomSheet/Category/MapChipList.tsx, src/components/BottomSheet/Preview/PreviewContentList.tsx, src/components/BottomSheet/ReviewPhotos.tsx, src/components/BottomSheet/TagList.tsx, src/constants.ts, src/layout/AppLayout.tsx, src/store/useBottomSheetStore.ts
#12 
#27 
<br><br>
바텀시트 conflict 문제를 해결했습니다.
<br><br>
<br><br>
<br><br>
=> Feat/#12 bottom sheet 구현

src/components/BottomSheet/BottomSheet.tsx, src/components/BottomSheet/Category/CategoryButton.tsx
#38 
<br><br>
카테고리 버튼 필터링 추가
<br><br>
이 화면에서 버튼 클릭했을 때 카테고리 필터링 되는 부분도 구현했습니다
<br><br>
<br><br>
=> Feat/#38 카테고리 버튼 필터링 추가

src/api/placeApi.ts, src/components/BottomSheet/BottomSheet.tsx, src/components/BottomSheet/DetailContent.tsx, src/components/BottomSheet/Preview/PreviewContentList.tsx, src/components/BottomSheet/Review/Review.tsx, src/components/BottomSheet/ReviewWrite/ReviewTagList.tsx, src/components/BottomSheet/ReviewWrite/ReviewWrite.tsx, src/components/BottomSheet/TagList.tsx, src/pages/Solmap.tsx, src/places.ts, src/types.ts
#40 
<br><br>
placeApi에서 fetchPlaces 작성
fetch해온 places로 setPlaces 하기
TagType 수정
<br><br>
<br><br>
<br><br>
=> Feat/#40 react query로 place fetch하기

src/api/reviewApi.ts, src/components/BottomSheet/Review/Review.tsx, src/components/BottomSheet/Review/ReviewList.tsx, src/types.ts
#43 
<br><br>
* types.ts 파일에서 interface ReviewProps를 type ReviewType으로 변경
* ReviewType의 tags 속성 자료값을 string[]에서 TagType[]으로 변경
<br><br>
<br><br>
<br><br>
=> Refactor/#43 review의 tags를 tagtype으로 변경

src/components/BottomSheet/Category/CategoryButton.tsx, src/components/BottomSheet/ContentTitle.tsx, src/components/BottomSheet/DetailContent.tsx, src/components/BottomSheet/ReviewPhotos.tsx, src/components/BottomSheet/ReviewRange.tsx, src/components/Sollect/SollectPhoto.tsx, src/components/global/TitleHeader.tsx, src/interface.ts, src/pages/RelatedSollect.tsx, src/routes/AppRouter.tsx, src/types.ts
#68 
<br><br>
바뀐 스타일링 수정
Url 공유 기능 추가
<br><br>
<br><br>
<br><br>
=> Feat/#68 Preview 스타일링 수정

src/api/searchApi.ts, src/components/Searching/MapSearchBar.tsx, src/components/Searching/RecentSearch.tsx, src/components/Searching/RecentSearchList.tsx, src/components/Searching/SearchArea.tsx, src/components/Searching/SearchBar.tsx, src/components/Searching/SearchPanel.tsx, src/components/Sollect/SollectGNB.tsx, src/pages/SearchPage.tsx, src/pages/SollectPage.tsx, src/pages/Solmap.tsx, src/routes/AppRouter.tsx, vite.config.ts
#82 
<br><br>
검색창 리팩토링
검색창 페이지 생성
최근 검색어 api 연동
<br><br>
<br><br>
<br><br>
=> Feat/#82 검색창 리팩토링, 최근 검색어 api 연동

src/api/sollectApi.ts, src/api/urls.ts, src/components/Sollect/PopularSollectPhoto.tsx, src/components/Sollect/SollectMark.tsx, src/components/Sollect/SollectPhoto.tsx
#106
<br><br>
쏠렉트 쏠마크 등록, 삭제 api 연동
쏠마크로 쏠렉트의 id 전달
<br><br>
<br><br>
<br><br>
=> Feat/#106 쏠렉트 쏠마크 등록, 삭제 api 연동

src/components/BottomSheet/Review/Review.tsx, src/components/BottomSheet/Review/ShowAllReviewsButton.tsx, src/routes/AppRouter.tsx
#117 
<br><br>
리뷰 페이지를 전체화면으로 변경
리뷰 하단에 border 추가
<br><br>
<br><br>
<br><br>
=> Refactor/117 리뷰 디자인 피드백 반영

Dockerfile, nginx/default.conf
#135 
<br><br>
github action과 GCP로 배포하기 위해 Dockerfile과 Nginx 설정 파일을 작성했습니다. 
<br><br>
<br><br>
<br><br>
=> [chore/#135] 웹페이지 배포 파일 작성

README.md
#137
<br><br>
<br><br>
<br><br>
<br><br>
=> [test/#137] github actions CI/CD를 통한 GCP 배포 테스트 

.github/workflows/main.yml
#140 
<br><br>
github action 워크플로우 파일 작성
<br><br>
<br><br>
<br><br>
=> [doc/#140] github action 워크플로우 파일 작성

.github/workflows/main.yml
<br><br>
<br><br>
<br><br>
<br><br>
=> [hotfix] workflow 파일에 환경변수 추가

src/App.tsx
<br><br>
tsconfig.json 파일의 compilerOptions에 noUnusedLocals와 noUnusedParameters가 true로 되어있어, 사용하지 않는 지역 변수와 함수 파라미터가 있으면 오류가 발생됩니다. 따라서 `npx eslint . --fix` 명령어로 사용하지 않는 코드를 검색하고 지워서 해결했습니다. 
<br><br>
<br><br>
<br><br>
=> [chore] 사용하지 않는 코드 제거

src/components/Solroute/SolrouteTitle.tsx, src/pages/SolrouteWritePage.tsx, src/store/solrouteWriteStore.ts
#157
<br><br>
typo 수정
<br><br>
<br><br>
<br><br>
=> [fix/#157] typo 수정

src/pages/Solmap.tsx
#166
<br><br>
개발을 위해 작성했던 실시간 위치 하드코딩을 제거했습니다. 
<br><br>
<br><br>
만약 실시간 위치를 다시 특정 위치로 특정하여 개발하고 싶다면 아래 사진처럼 Solmap.tsx에서 수정하세요. (커밋시에는 적용하지 않도록 주의해주세요)
<br><br>
=> [refactor/#166] 실시간 위치 하드코딩 제거

src/utils/icon.ts
src > utils > icon.ts 파일의 22번째 줄 경로명 일부인 DrinkBlack.svg을 drinkBlack.svg로 수정했습니다.
=> [fix] icon Asset 경로 수정

src/components/Solmark/SolmarkContentMy.tsx, src/components/Solmark/SolmarkContentSollect.tsx, src/components/Solmark/SolmarkNoResult.tsx
<br><br>
<br><br>
<br><br>
<br><br>
=> [fix/#170] 빌드 오류 수정

src/api/placeApi.ts, src/api/sollectApi.ts, src/components/BottomSheet/SolmarkChip.tsx, src/components/Place/PreviewContentSummary.tsx, src/components/Sollect/PopularSollectPhoto.tsx, src/components/Sollect/SollectDetail/SollectDetailBottomBar.tsx, src/components/Sollect/SollectDetail/SollectDetailHeader.tsx, src/components/Sollect/SollectGroup/SollectGroup.tsx, src/components/Sollect/SollectGroup/SollectGroupList.tsx, src/components/Sollect/SollectList.tsx, src/components/Sollect/SollectMark.tsx, src/components/Sollect/SollectNoResult.tsx, src/components/Sollect/SollectPhoto.tsx, src/components/Solmark/SolmarkContentMy.tsx, src/components/Solmark/SolmarkContentSollect.tsx, src/components/Solmark/SolmarkNoResult.tsx, src/components/Solmark/SolmarkPlaceListCard.tsx, src/components/Solmark/SolmarkTab.tsx, src/components/global/EditDeletePopover.tsx, src/interface.ts, src/pages/RelatedSollect.tsx, src/pages/SollectSearchResultPage.tsx, src/pages/SolmarkPage.tsx, src/pages/SolmarkPlacePreviewPage.tsx, src/store/sollectStore.ts, src/types.ts
리팩토링과 사소한 변경사항들을 수정했습니다
#176 
<br><br>
SollectList의 sollects prop를 없애고, 추천 쏠렉트에서만 recommendSollects를 보내도록 수정
(추천 쏠렉트는 한 페이지에서 다 보여주는 경우가 있어서 동시에 여러 데이터를 store로 관리하기 어렵기 때문)
수정삭제 팝오버 리팩토링
추천 쏠렉트, 인기 쏠렉트 등 모든 sollectApi를 privateAxios로 변경(isMarked를 위해)
모든 placeApi를 privateAxios로 변경(isMarked를 위해)
<br><br>
<br><br>
<br><br>
=> Refactor/#176 쏠마크, 쏠렉트 리팩토링

src/api/searchApi.ts, src/api/solmarkApi.ts, src/api/urls.ts, src/components/Place/PreviewContentSummary.tsx, src/components/Searching/RelatedSearchPlace.tsx, src/components/Searching/RelatedSearchPlaceList.tsx, src/components/Sollect/SollectWrite/SollectWriteAddedPlace.tsx, src/components/Sollect/SollectWrite/SollectWritePlaces.tsx, src/components/Solmark/SolmarkContentPlace.tsx, src/components/Solmark/SolmarkPlaceListCard.tsx, src/components/global/LargeButtonInverted.tsx, src/components/global/SelectableChip.tsx, src/layout/SolroutePlaceAddLayout.tsx, src/pages/SolmarkPlacePreviewPage.tsx, src/pages/SolroutePlaceAddPage.tsx, src/pages/SolrouteWritePage.tsx, src/routes/AppRouter.tsx, src/store/searchStore.ts, src/store/sollectWriteStore.ts, src/store/solrouteWriteStore.ts, src/types.ts
#183
<br><br>
쏠마크와 장소 검색을 통해 쏠루트 장소를 주가할 수 있다.
<br><br>
<br><br>
<br><br>
=> Feat/#183 쏠루트 장소 쏠마크에서 추가

src/components/Searching/SearchBar.tsx
#193
<br><br>
SearchBar 확대(scale) 비율에 따른 input width 및 margin 조정했습니다. 
<br><br>
<br><br>
<br><br>
=> [fix/#193] SearchBar 확대(scale) 비율에 따른 input width 및 margin 조정

src/api/searchApi.ts, src/components/Searching/RelatedSearchPlace.tsx, src/components/Solroute/SolroutePlace.tsx
#205 
<br><br>
쏠루트 : 코스에서 추가한 장소 배경 색상을 수정했습니다. 
<br><br>
<br><br>
<br><br>
=> Refactor/#205 쏠루트 생성시 추가된 장소 스타일 수정

src/components/Searching/SearchBar.tsx
#207 
<br><br>
검색창 최대 글자수를 50자로 설정
<br><br>
<br><br>
Searching 폴더의 SearchBar.tsx를 사용하는 모든 검색창에 해당됩니다. 
<br><br>
=> [feat/#207] 검색창 최대 글자수 50자로 설정

src/components/Solroute/SolroutePlace.tsx
메모 존재 여부에 따라 다르게 했습니다.
#209 
<br><br>
쏠루트 생성에서 추가된 장소 삭제 시 바로 삭제되는 것 이 아니라 장소를 정말 삭제할 것이냐 묻는 팝업이 뜹니다. 이는 메모 작성 여부에 따라서 다릅니다. 
<br><br>
<br><br>
<br><br>
=> [feat/#209] 장소 삭제 시 팝업 구현

src/components/BottomSheet/ReviewWrite/ReviewEmoji.tsx, src/layout/SollectWriteLayout.tsx, src/pages/ReviewWritePage.tsx, src/store/reviewWriteStore.ts, src/store/sollectWriteStore.ts, src/types.ts
#213 
<br><br>
* 이모지 로그인된 상태일 경우만 선택 가능
* 리뷰 작성시 이전 리뷰 데이터 남아있는 문제 해결
* 쏠렉트 작성시 이전 데이터 남아있는 문제 해결
이모지는 로그인된 상태에 따라 분기처리해 해결
이전 데이터 남아있는 문제는 store에 reset 함수를 둬 문제 해결
<br><br>
<br><br>
<br><br>
=> Feat/#213 store로 인해 이전 데이터가 남아있는 문제 해결

src/components/Sollect/SollectWrite/SollectWriteTitle.tsx, src/components/global/FilePicker.tsx, src/components/global/Warn.tsx, src/index.css, src/layout/SollectWriteLayout.tsx, src/main.tsx, src/pages/solroute/SolrouteWritePage.tsx
#219 
<br><br>
* 토스트 길이 좌우 16px 제외 최대한으로 늘림
* 토스트 명 변경된 문구로 변경
* thumbnail 이미지 파일 크기 체크 못하던 오류 해결
<br><br>
<br><br>
<br><br>
=> Feat/#219 토스트 변경

src/api/solrouteApi.ts, src/layout/SollectWriteLayout.tsx, src/pages/ReviewWritePage.tsx, src/pages/solroute/SolrouteWritePage.tsx
#215 
<br><br>
* useMutation의 isPending을 이용해 api 처리 중 등록 버튼 비활성화
* 쏠렉트 등록 중 등록 버튼 비활성화
* 리뷰 등록 중 등록 버튼 비활성화
* 쏠루트 등록 중 등록 버튼 비활성화
<br><br>
<br><br>
<br><br>
=> Feat/#215 api 생성 중일 때 버튼 비활성화

src/components/Solroute/SolrouteTitle.tsx, src/pages/solroute/SolrouteDetailPage.tsx
#230 
<br><br>
* 쏠루트 제목 입력 너비 키움
* 쏠루트 조회 후 뒤로갈 때 reset() 함수 호출. -> 코스 생성시 초기화된 상태로 작성 가능
<br><br>
<br><br>
<br><br>
=> Fix/#230 쏠루트 조회 오류 수정

src/api/solrouteApi.ts, src/components/Solroute/SolrouteMap.tsx, src/components/Solroute/SolroutePreviewCard.tsx, src/components/Solroute/SolrouteTitle.tsx, src/components/Solroute/StatusChip.tsx, src/pages/solroute/SolrouteDetailPage.tsx, src/pages/solroute/SolroutePage.tsx, src/pages/solroute/SolrouteWritePage.tsx
#227 
<br><br>
- SolrouteMap: props로 장소 정보 전달 지원 및 마커 렌더링 최적화
- SolrouteDetailPage: 수정 시 기존 데이터 설정 및 수정 페이지 이동 개선
- SolrouteWritePage: 수정 모드 추가 및 임시저장 모달 UI 개선
- 제목 15자 초과 시 ... 표시 및 말줄임 기능 개선
- 토글 버튼 세로 늘어짐 문제 해결 (self-stretch 제거)
- 제목 컨테이너 min-width 설정으로 텍스트 overflow 수정
- StatusChip 컴포넌트 일관된 스타일 적용
<br><br>
https://github.com/user-attachments/assets/8fef4c06-08f5-419e-8b1c-f9acf723aa2b
<br><br>
<br><br>
=> Feat/#227 쏠루트 수정 로직 구현

src/pages/profile/SettingPage.tsx, src/store/placeStore.ts, src/store/searchStore.ts, src/store/sollectDetailStore.ts, src/store/sollectStore.ts, src/store/solmarkStore.ts
#260 
<br><br>
clear store
캐시 삭제
<br><br>
<br><br>
<br><br>
=> [fix/#260] 로그아웃 시 store 삭제, 캐시 삭제

src/api/axios.ts, src/auth/LoginButtons.tsx, src/auth/LoginModal.tsx, src/auth/LoginRequiredAction.tsx, src/auth/OAuthCallback.tsx, src/components/Sollect/SollectDetail/AddCourseButton.tsx, src/routes/AppRouter.tsx, src/routes/ProtectedRoute.tsx, src/store/locationStore.ts
#255 
<br><br>
* 로그인 모달 구현 방식을 개선했습니다.
* 비 로그인 상태에서 로그인 필수 페이지를 Url로 접근할 경우 login 화면으로 redirect됩니다.
* 로그인 한 사용자의 토큰이 유효하지 않으면 Login 화면으로 redirect 됩니다.
* 코스로 저장 클릭시 로그인 여부를 확인합니다.
<br><br>
https://github.com/user-attachments/assets/f7602d25-870a-4f2c-a3f5-a29709c7a619
<br><br>
**AppRouter** 확인 
a1399c38f6af453d13e5149ca0ec6db90a881dfb
변경된 AppRouter 확인 부탁드립니다.
제가 아는 선에서 로그인 필요 페이지와 아닌 페이지를 구분했습니다.
혹시 잘못 구분된 페이지가 있다면 수정 부탁드립니다.
사용법: cfe9e279201de80a6fa1e6b76b446dc26786beb1
로그인 필수인 페이지는 아래 Route로 감싸주면 됩니다.
```
<Route element={<ProtectedRoute isLoggedIn={isLoggedIn} />}>
{로그인 필요한 라우터}
</Route>
```
<br><br>
=> Refactor/#255 authentication 개선

src/components/Sollect/SollectDetail/AddCourseButton.tsx, src/components/Sollect/SollectWrite/SollectWriteImageInput.tsx, src/hooks/useKeyboardAdjustment.ts, src/pages/solroute/SolrouteDetailPage.tsx
#268 
<br><br>
* 쏠루트 조회시 장소 아이콘 번호 1부터 보이도록 설정
* 쏠렉트 작성 페이지 visualViewPort resize될 때에도 위치 변경되도록 수정
<br><br>
<br><br>
<br><br>
=> Feat/#268 기타 수정 사항

src/components/global/selectableIconSet/IconAddButton.tsx, src/components/global/selectableIconSet/SelectableIconSet.tsx
#276 
<br><br>
아이콘 선택시 모달 딛히도록 수정
<br><br>
<br><br>
<br><br>
=> [feat/#276] 아이콘 모달 선택시 모당 창 닫힘

src/components/BottomSheet/DetailContent.tsx, src/components/BottomSheet/Preview/PreviewContentList.tsx, src/components/Solroute/SolrouteMap.tsx, src/pages/ReviewsPage.tsx, src/pages/SollectSearchResultPage.tsx, src/pages/solroute/SolrouteDetailPage.tsx
<br><br>
<br><br>
<br><br>
<br><br>
=> [fix/#274] 로딩중 텍스트 삭제

src/components/Profile/NicknameInput.tsx, src/pages/profile/AddPlacePage.tsx
#281 
<br><br>
useInputAdjustScale를 이용해 ios에서 닉네임 입력시 확대되는 문제를 해결했습니다.
<br><br>
<br><br>
<br><br>
=> [feat/#281] 닉네임 입력시 확대되는 문제 해결

src/components/BottomSheet/ContentTitle.tsx
타이틀, 카테고리 글자수 표시 변경
#293 
<br><br>
<br><br>
<br><br>
<br><br>
=> [feat/#293] 타이틀, 카테고리 글자수 표시 변경

src/components/Sollect/SollectDetail/AddCourseButton.tsx
#292 
<br><br>
코스로 저장 성공시 toast로 알림
<br><br>
<br><br>
<br><br>
=> [feat/#292] 코스로 저장 성공시 토스트로 알림

src/api/searchApi.ts
#306 
<br><br>
최근 무한 스크롤 형식으로 api가 변경됐으나
다시 기존 형식 api로 변경됨.
이 때문에 장소 검색 결과가 화면에 안 나타나는 문제가 발생함.
기존 api로 변경해 문제를 해결함
<br><br>
<br><br>
<br><br>
=> [fix/#306] 장소 검색 api 변경

src/api/searchApi.ts, src/components/Searching/RelatedSearchList.tsx, src/components/Searching/RelatedSearchPlaceList.tsx
#312 
<br><br>
* `getRelatedSearchPlaces` 함수에 `userLatLng.lat`, `userLatLng.lng` 추가
* `RelatedSearchList`에 장소 추가 로직 제거
<br><br>
<br><br>
<br><br>
=> Feat/#312 장소 검색시 사용자 위치 추가

src/auth/OAuthCallback.tsx
* [feat/#232] 본문 pt-16 변경 및 배경 이미지에 bg-black/50 추가
* [feat/#232] 작성 전 다음 버튼 색상 primary-400으로 변경
* [feat/#232] 쏠렉트 이미지 추가 하단 바 키보드 위로 고정
현재 100% 작동하지 않음.
추후 개선 필요
* [fix/#239] 쏠루트 장소 추가 엔토 오류 수정
* [feat/#239] 장소 검색 isMarked 추가
* [feat/#239] 장소 주소명 길어져도 형태 유지
* [fix/#221] 머지 충돌 수정
* [feat/#221] 프로필 메뉴 구현
* [feat/#221] 회원 화면, 간편 로그인 버튼
* [feat/#221] 프로필 수정
* [feat/#221] 유저 정보 받아오기
* [feat/#221] 프로필 수정 구현
* [fix/#221] 쏠렉트 카테고리 검색 안되는 오류 수정
* [fix/#221] 쏠렉트 포토 너비 수정
* [feat/#221] 공지사항 페이지
* [fix/#221] 태그 헤더 임시 수정
* [feat/#221] 공지사항 페이지
* [feat/#221] 공지 디테일 조회
* [feat/#221] 의견 남기기
* [feat/#221] 장소 추가 요청
* [feat/#221] 빌드 되도록 수정
* [feat/#221] 공지사항 상세 조회 id로 반영
* [fix/#243] 쏠맵 X 버튼 navigate 프리뷰 말고는 다 맵으로 돌아가도록 수정
* [fix/#243] navigate from 전달
* [feat/#243] /는 /sollect로 redirect
* [fix/#243] 프사 …
=> Release: 2025년 8/5 03:40 배포 (#320)

src/components/BottomSheet/BottomSheet.tsx
#324 
<br><br>
컴퓨터에서 바텀시트 클릭 안되는 문제 해결
<br><br>
<br><br>
컴퓨터에서 바텀시트 버튼들이 클릭 안되는 문제의 원인은 BottomSheet.tsx의 `handlePointerDown`의 `setPointerCapture` 함수 때문에 발생하던 문제였어요.
해당 함수는 클릭한 요소를 벗어나도 계속 이벤트를 잡도록 만드는 함수예요.
즉, setPointer 후 releasePointer 할 때까지 다른 click event를 무시하게 돼요.
그러면 모바일에서도 안되어야 하는거 아닌가? 라고 생각할거에요.
모바일에서 됐던 이유는 브라우저에서 자동으로 click 이벤트를 생성하기 때문이에요.
> Browsers typically dispatch emulated mouse and click events when there is only a single active touch point.
그래서 mouse event라면 click 이벤트를 dispatch해 버튼이 클릭 안되는 문제를 해결했습니다!
<br><br>
https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Using_Touch_Events?utm_source=chatgpt.com
=> [fix/#324] 컴퓨터 bottomsheet 클릭 문제 해결

src/components/Searching/SearchArea.tsx
#328 
<br><br>
쏠루트 장소 추가 완료시 바로 쏠루트 작성 페이지로 이동
<br><br>
<br><br>
<br><br>
=> [faet/#328] 쏠루트 장소 추가 완료시 바로 쏠루트 작성 페이지로 이동

src/pages/solroute/SolrouteDetailPage.tsx
<br><br>
이 pull request는 SolrouteDetailPage 컴포넌트의 컨테이너에 사소한 UI 변경을 적용합니다. onMouseDown과 onTouchStart 이벤트 핸들러를 외부 컨테이너에서 내부 컨테이너로 이동했습니다. 이 변경은 사용자 상호작용이 UI에서 처리되는 방식에 영향을 줄 수 있습니다.
<br><br>
<br><br>
<br><br>
=> Release: 2025년 8/24 18:20 배포
