src/components/Searching/AutoSearchList.tsx
src/components/Searching/RecentSearchList.tsx
src/components/Searching/SearchArea.tsx
src/components/Searching/SearchBar.tsx
src/components/Searching/SearchPanel.tsx
src/components/XButton.tsx
src/components/XButtonCircle.tsx
src/hooks/useDebounce.ts
src/pages/Solmap.tsx
src/store/searchStore.ts

#20 
<br><br>
- Solmap 페이지에 SearchArea(검색창 영역)을 연결했습니다.
- 피그마의 SearchPanel(Searching 화면)을 구현했습니다.
- zustand 상태관리를 통해서 다음을 구현했습니다.
- SearchBar(검색창)의 값이 공유되도록 했습니다.
- SearchArea를 하나로 공유하며 focusing에 따라 SearchPanel을 보이도록 했습니다.
- SearchBar의 inputValue를 관리하며 값에 따라 '최근 검색어'와 '검색 결과' 컴포넌트가 보이도록 했습니다. 
- 추후 사용자의 입력값을 api 호출에 이용하기 위해 debouncing을 미리 적용하여 콘솔에 출력되도록 구현했습니다. 
<br><br>
<br><br>
- debouncing 텀은 1초로 설정했습니다.
- Solmap의 SearchArea(검색창 영역)은 z-100으로 해두었습니다.  
- SearchPanel(Searching 화면)은 z-70으로 해두었습니다.
- SearchPanel 에  bg 값이 #fff인데 색상코드에 없어서 우선 bg-[#fff]로 작성했습니다. 
- ★ Solmap에서 SearchBar(검색창)을 클릭하면 아래 사진처럼 구조상 BottomNav가 보입니다. 만약 Searching 화면에서 BottomNav가 안 보이도록 해야한다면 BottomNav 컴포넌트 수정이 필요할 것 같습니다. 
<br><br>
[검색 기능 구현](https://velog.io/@shagrat/%EC%A2%8C%EC%B6%A9%EC%9A%B0%EB%8F%8C-%EA%B5%AC%EA%B …

Feat/#20 SearchPanel 구현

---

src/assets/currentLocation.svg
src/components/BottomSheet/CurrentLocationButton.tsx
src/interface.ts
src/pages/MapSheet.tsx

#42 
<br><br>
현위치로 지도 이동 버튼 UI 구현
마커 클릭 시 마커가 지도의 가운데보다 살짝 위로 오게 수정
(둘 다 희정님이 구현해주신 기능 거의 그대로 사용했습니다 😚🙏)
현위치 아이콘 svg 받아오기
현위치 버튼 바텀시트 따라서 이동하기
바텀시트가 가장 위에 있으면 현위치 버튼 숨기기
<br><br>
<br><br>
현위치 svg는 assets 폴더에 currentLocation.svg로 저장해두었습니다.
<br><br>

Feat/#42 현위치로 지도 이동 버튼

---

src/components/BottomSheet/ContentTitle.tsx
src/components/BottomSheet/Preview/PreviewContent.tsx
src/components/XButton.tsx

#47 
<br><br>
프리뷰 -> 디테일 : 프리뷰로 이동 /map/list
특정 장소 검색 : 쏠맵 메인화면으로 이동 /map
XButton DetailContent에서도 쓸 수 있도록 수정 (검색창이랑 border-radius가 다름)
<br><br>
<br><br>
DetailContent의 ContentTitle 컴포넌트랑 SearchArea에서 쓰이는 XButton의 border-radius가 달라서 수정을 했습니다.
ContentTitle에서 XButton을 쓸 때
detail 을 props로 함께 넘겨주어서 스타일을 다르게 적용시켰습니다.
기존에 XButton을 쓰던 컴포넌트에서는 따로 수정안해도 되게 detail을 Optional Property로 두었습니다!! 원래 쓰던 대로 쓰시면 됩니다
<br><br>

Feat/#47 DetailContent 뒤로가기 XButton 구현

---

src/components/Map/MapSheet.tsx
src/utils/icon.ts
src/utils/mapFunc.ts
src/utils/markerFunc.ts

#96 
<br><br>
MapSheet.tsx의 과도한 책임 분산 문제를 해결하고, 관심사 분리 및 가독성 향상을 위해 지도 관련 함수와 마커 관련 함수를 별도 파일로 분리하였습니다.
기존에는 모든 로직이 한 파일에 집중되어 있었습니다. 이번 리팩토링을 통해 각 기능이 명확히 구분되며, 코드 관리가 용이해졌습니다.
<br><br>
<br><br>
각 기능을 별도 파일로 분리하여 MapSheet.tsx의 과도한 책임을 분산시켰습니다.
다만, 함수 분리로 인해 여러 인자를 전달해야 하는 번거로움이 생겼고,
해당 함수들이 실제로 다른 파일에서 재사용될 가능성은 낮아 보입니다.
👉 이런 경우에도 기능 분리와 모듈화가 적절한 방식인지에 대한 의견이 궁금해요! 
구조적인 관점에서 유지보수성/가독성 개선이 더 우선인지, 아니면 실제 재사용 가능성을 기준으로 판단해야 하는지 리뷰 부탁드립니다 :) 
<br><br>

Refactor/#96 유지보수와 재사용성을 위한 MapSheet.tsx의 함수 분리

---

src/components/Searching/RelatedSearchList.tsx

#114 
<br><br>
사용자의 실시간 좌표로 getRelatedSearchWords를 호출하도록 했습니다.
단, 사용자가 위치정보를 허용하지 않을 시 좌표가 0,0으로 설정됩니다.
<br><br>
위 사진) 실시간 좌표 적용 전
<br><br>
위 사진) 실시간 좌표 적용 후
<br><br>
<br><br>

[feat/#114] 사용자의 실시간 좌표로 getRelatedSearchWords 호출

---

src/api/urls.ts
src/components/Searching/RecentSearchList.tsx
src/components/Searching/RelatedSearchList.tsx
src/components/Searching/SearchBar.tsx
src/routes/AppRouter.tsx

#112 #114 
<br><br>
쏠맵(SoMap)의 최근 검색어 및 검색 실행(엔터 동작) 관련 오류를 수정했습니다.
쏠렉트(Solect)와 쏠맵의 pathname에 따라 검색 동작을 분기처리하도록 되어 있었으나,
내부적으로 mode 값이 "map"으로 잘못 지정되어 쏠맵에서 403 에러가 발생하는 문제가 있었습니다.
- mode 값을 "map" ➝ "solmap" 으로 올바르게 수정하여 쏠맵 환경에서도 403 오류가 발생하지 않도록 처리
- SearchBar, RecentSearchList, RecentSearch 등 관련 컴포넌트의 분기처리는 잘 되어 있었으며, 내부 상태값만 수정
- 쏠맵에서 검색어 입력 후 Enter 시:
연관 검색어가 존재하면 → 쏠맵의 프리뷰 화면으로 이동
연관 검색어가 없으면 → "검색 결과 없음" 화면으로 이동하도록 설정
<br><br>
쏠맵의 엔터 동작 분기 처리 
<br><br>
<br><br>

[Feat/#112] 쏠맵 최근 검색 및 엔터 동작 추가 구현 

---

package-lock.json
package.json
src/api/mapApi.ts
src/api/placeApi.ts
src/api/searchApi.ts
src/api/urls.ts
src/components/BottomNav.tsx
src/components/BottomSheet/Category/CategoryButton.tsx
src/components/BottomSheet/Category/MapChip.tsx
src/components/BottomSheet/DetailContent.tsx
src/components/BottomSheet/Preview/PreviewContentEmpty.tsx
src/components/BottomSheet/Preview/PreviewContentList.tsx
src/components/Map/MapSheet.tsx
src/components/Searching/RecentSearch.tsx
src/components/Searching/RelatedSearch.tsx
src/components/Searching/RelatedSearchList.tsx
src/components/Searching/SearchBar.tsx
src/pages/Solmap.tsx
src/store/mapStore.ts
src/store/markerStore.ts
src/store/placeStore.ts
src/store/searchStore.ts
src/utils/geolocation.ts
src/utils/icon.ts
src/utils/mapFunc.ts
src/utils/placeFunc.ts

#133 
<br><br>
쏠맵에서 지도에 표시할 마커와 PreviewContentList, DetailContent에 표시할 데이터를 서버로부터 받아올 수 있도록 api를 연결했습니다.
작업 내용이 많은데 아래 표로 각 커밋의 주요 내용을 정리해봤습니다. 자세한 내용은 커밋 메시지를 참고해주세요. 코드 변경 내역은 'feat/#133' 브랜치를 로컬에 받아서 커밋별 파일 변경 내역을 vscode 로 확인하는 것이 눈에 더 잘 들어옵니다.
| Commit | Commit Title | Description |
|--------|--------------|-------------|
| b667b34 | [feat/#133] 마커 클릭시 상세 정보 조회 | (필요 없는 커밋) |
| 33ff0cf | [fix/#133] 마커 클릭시 상세정보 화면으로 이동 및 api 호출 | 화면에 보이는 마커를 클릭하면 해당 마커의 상세 페이지로 이동함. |
| 5eeeb85 | [refactor/#133] 사용자의 실시간 위치 추적 로직으로 변경 및 관련 코드 정리 | 사용자의 위치를 실시간으로 받아오는 함수를 작성하여 solmap.tsx에서 호출함. |
| d427583 | [fix/#133] 마커 재검색 시 결과가 없을 경우 이전 마커가 남아있는 오류 수정 | '이 지역에서 검색' 버튼 클릭시 결과가 없을 때, 지도에 표시 되어있는 이전 마커는 지우고 결과 없음을 반영하도록 수정함. |
| 885935f | [feat/#133] 검색 결과 없을 때 사용자 거리 기반 추천 API 연동 및 콘솔 출력 | 검색창에서 검색 …

Feat/#133 solmap api 연동

---

src/components/Searching/RelatedSearchPlace.tsx
src/components/Sollect/SollectWrite/SollectWriteAddedPlace.tsx
src/components/Sollect/SollectWrite/SollectWriteHeader.tsx
src/components/Sollect/SollectWrite/SollectWritePlaces.tsx
src/components/Solroute/SolrouteMap.tsx
src/components/Solroute/SolroutePlaceAddButton.tsx
src/components/Solroute/SolrouteTitle.tsx
src/pages/SolrouteWritePage.tsx
src/routes/AppRouter.tsx
src/store/sollectWriteStore.ts
src/store/solrouteWriteStore.ts
src/types.ts

#153
<br><br>
쏠루트 작성 page와 store인 solrouteWritePage를 생성함
<br><br>
<br><br>
```
export type RelatedSearchWord = {
address: string | null;
category: string | null;
distance: {
unit: string;
value: number;
};
id: number | null;
name: string;
type: 'DISTRICT' | 'PLACE';
};
export type RelatedSearchPlace = RelatedSearchWord & {
isAdded: boolean;
};
export type SolroutePlace = RelatedSearchPlace & {
memo: string;
latitude: number;
longitude: number;
};
```
쏠루트 store에 사용할 place 타입으로 SolroutePlace를 만들었습니디다
기존 RelatedSearchPlace에 memo, latitude, longitude를 추가했습니다.
다만 쏠마크의 place와도 연동되어야할 수 있어 추후 변동될 수도 있을 것 같아요!
자유롭게 변동해주셔도 됩니다.
<br><br>

Feat/#153 쏠루트 작성 기본 구조 생성

---

src/api/placeApi.ts
src/api/reviewApi.ts
src/api/sollectApi.ts
src/api/urls.ts
src/components/BottomSheet/ContentTitle.tsx
src/components/BottomSheet/DetailContent.tsx
src/components/BottomSheet/Preview/PreviewContent.tsx
src/components/BottomSheet/Preview/PreviewContentEmpty.tsx
src/components/BottomSheet/Preview/PreviewContentList.tsx
src/components/BottomSheet/Preview/PreviewPhotos.tsx
src/components/BottomSheet/SolmarkChip.tsx
src/components/BottomSheet/Tag.tsx
src/components/BottomSheet/TagList.tsx
src/components/Map/MapSheet.tsx
src/components/Place/PreviewContentSummary.tsx
src/components/Sollect/SollectDetail/SollectDetailHeader.tsx
src/components/global/Modal.tsx
src/pages/RelatedSollect.tsx
src/pages/Solmap.tsx
src/routes/AppRouter.tsx
src/store/placeStore.ts
src/store/reviewWriteStore.ts
src/types.ts

#151 
<br><br>
프리뷰 무한 스크롤 구현
`placesRegionQuery`, `placesIdListQuery`, `placesDisplayQuery` 각각 무한 스크롤 쿼리 적용하고,
queryType에 따라 activeQuery를 결정해서 activeQuery의 places가 리스트에 보이도록 구현
api response에 맞게 렌더링 수정
1. Place
Place는 프리뷰와 디테일 정보에서 공통으로 들어가는 필드를 BasePlace로 두고,
DetailPlace와 PreviewPlace로 구분해서 구현
2. Tag
Tag의 api response
- string 배열로 오는 경우
- mood, solo로 오는 경우 {tagName, tagTotal}
mood, solo로 오는 경우에만 TagType ({tagName:string, tagTotal:number}) 사용.
string [] 으로 오면 Type 따로 사용하지 않음
따라서 TagList는 tags와 detailTags 둘 중 하나를 받음
tags는 string[]
detailTags는 TagType[]
디테일 뷰 외에는 모두 tags로 전달하면 될 것 같다. (Review에서도 tags로)
검색 결과가 없을 때 보여주는 추천 장소를 저장하기 위해
placeStore에 `recommendedPlaces` 추가
이 지역에서 검색 버튼을 눌렀을 때 리스트가 재설정 되어야하는데,
MapSheet에서도 무한스크롤 쿼리를 넣으면 코드가 중복되는 게 많을 것 같아서
placeStore에 `refreshTrigger` 변수를 추가. …

Feat/#151 쏠맵 프리뷰, 디테일 페이지

---

src/api/sollectApi.ts
src/api/solmarkApi.ts
src/api/urls.ts
src/auth/OAuthCallback.tsx
src/components/BottomSheet/SolmarkChip.tsx
src/components/Place/PreviewContentSummary.tsx
src/components/Sollect/SollectDetail/SollectDetailHeader.tsx
src/components/Sollect/SollectList.tsx
src/components/Sollect/SollectPhoto.tsx
src/components/Solmark/SolmarkContentMy.tsx
src/components/Solmark/SolmarkContentSollect.tsx
src/components/Solmark/SolmarkNoResult.tsx
src/components/Solmark/SolmarkTab.tsx
src/components/global/EditDeletePopover.tsx
src/interface.ts
src/pages/SolmarkPlacePreviewPage.tsx
src/routes/AppRouter.tsx
src/store/sollectDetailStore.ts

#170 
<br><br>
쏠마크 쏠렉트, 마이 페이지를 구현했습니다.
저장한 쏠렉트 조회 페이지 구현
내가 작성한 쏠렉트 조회 페이지 구현
수정 삭제 버튼 컴포넌트화 EditDeletePopover.tsx
로그인할 때 Local Storage에 userId를 저장하고 쏠렉트 작성자 id와 비교해서 동일할 때만 수정, 삭제 버튼 표시
<br><br>
<br><br>
수정 삭제 모달을 컴포넌트화했습니다.
kebab 버튼은 포함하지 않았기 때문에 수정 삭제 모달을 사용하려는 페이지에서 직접 만들어주어야 합니다!!
(SollectDetailHeader.tsx 참고)
코드가 꼬이는 게 있어서 안 했는데 나중에 컴포넌트에 kebab 버튼까지 포함해서 리팩토링해보고 싶네요..
<br><br>

Feat#170 쏠마크 쏠렉트, 마이 구현

---

src/components/Solroute/SolrouteMap.tsx
src/components/Solroute/SolroutePlace.tsx
src/pages/SolrouteWritePage.tsx
src/store/solrouteWriteStore.ts

#188 
<br><br>
기존의 하드코딩된 장소 정보를 삭제하고 '장소추가' 버튼을 통해 선택한 장소가 페이지에 나타나도록 했습니다.
추가된 장소의 trash 버튼을 누르면 해당 장소 정보를 Store의 placeInfo에서 삭제하도록 하여, 결과가 추가된 장소와 지도에 즉시 반영되도록 했습니다. 
SolroutePlace 컴포넌트의 line 부분을 드래그 앤 드롭으로 이동시킬 수 있으며, 결과가 추가된 장소와 지도에 즉시 반영되도록 했습니다.
<br><br>
<br><br>
마지막 사진처럼 그래그 할 때 특정 영역 안으로만 움직일 수 있도록 하는 기능이 있는지 조사하고 추후 디자인 수정할 때 함께 리팩토링 하겠습니다. 
<br><br>

Feat/#188 쏠루트 추가된 장소 띄우기

---

src/components/Sollect/SollectWrite/SollectWriteImageInput.tsx
src/components/global/FilePicker.tsx

#218 
<br><br>
1. 이미지 파일 크기 필터링 오류
env파일과 FilePicker의 변수명이 달라서 생긴 문제.
변수명을 동일하게 변경해 해결
2. 쏠렉트 이미지 개수 문제
우선, keepfiles를 true로 안해서 toast를 못 띄움
keepfiles를 true로 변경해 toast는 잘 나타났으나 file이 중복돼 나타나는 문제가 발생
FilePicker는 keepfiles = true일 때 기존 파일과 새로 선택된 파일을 합침.
하지만 해당 기능을 쏠렉트 이미지 추가 함수에서 처리하고 있어 중복 문제가 발생함.
이에 외부 함수만을 의존하겠다는 managedExternally 필드를 추가해 해결함
<br><br>
<br><br>
<br><br>

Fix/#218 이미지 처리 오류 해결

---

src/components/BottomSheet/Category/CategoryButton.tsx
src/components/Map/MapSheet.tsx
src/store/markerStore.ts

#263 
<br><br>
- CategoryButton 클릭 시 이전의 MapChip 카테고리 선택 상황과 무관하게 항상 카테고리 선택되도록 수정
- CategoryButton 클릭 하여 카테고리 변경 시 마커 검색 실행하여 사용자 경험 개선
- MapSheet의 재검색 함수에서 선택된 카테고리 유지하도록 수정
- 코드 포맷팅 및 불필요한 공백 제거
<br><br>
<br><br>
<br><br>

[fix/#263] 카테고리 버튼 클릭 시 마커 검색 및 상태 동기화 개선

---

src/components/Solroute/SolroutePlace.tsx

#272
<br><br>
메모의 onBlur를 이용해서 특정 시점에만 메모를 스토어에 저장하도록 하여 수정했습니다.
<br><br>
<br><br>
좋은 아이디어를 주신 태호님 감사합니다. 
<br><br>

[fix/#272] 쏠루트 메모 작성 때마다 마커 리렌더링 문제 해결

---

src/components/Solroute/SolrouteMap.tsx
src/store/solrouteWriteStore.ts

#275 
<br><br>
solrouteWriteStore의 palceInfos를 인식하지 못 한게 아니라, palceInfos.length가 0일 때는 return했기 때문에 마지막 마커가 지워지지 않았던 것이었습니다.
마커 추가 및 삭제 로직을 분리하여 문제를 해결했습니다. 
<br><br>
<br><br>
<br><br>

[fix/#275] 쏠루트 장소 삭제시 지도에 마커 남아있는 오류 해결

---

src/components/BottomSheet/Preview/PreviewContent.tsx
src/components/Map/MapSheet.tsx
src/store/mapStore.ts
src/store/markerStore.ts
src/utils/mapFunc.ts

#298 
<br><br>
- mapStore에 지도 인스턴스 및 지도 이동 함수를 추가하였습니다.
- PreviewContent 클릭시 해당 장소의 마커로 지도가 이동합니다.
- 지도에 표시된 마커 클릭시, 해당 마커가 가운데로 오도록 수정하였습니다.
- 검색시 (연관 검색어 클릭 및 엔터 동작 등) 마커가 1개일 때도 지도 가운데로 오도록 수정하려고 했지만 같은 로직이 동일하게 작동하지 않아 추후 결과가 다르게 나오는 이유를 알아봐야할 것 같습니다. 
<br><br>
https://github.com/user-attachments/assets/b8b9dcc8-58dc-4f24-8c46-65c7d0d953ee
<br><br>
<br><br>

feat/#298: 프리뷰 리스트 장소 클릭시 지도 이동

---

package-lock.json
package.json
src/api/axios.ts
src/auth/OAuthCallback.tsx
src/pages/Login.tsx
vite.config.ts

#288 
<br><br>
* refresh toekn 재발급 기능 구현
<br><br>
<br><br>
현재 refresh token 구현 부분에 refresh token cookie 동시성 문제를 해결하기 위해 queue를 이용함.
다만 이는 reissue-token 요청시 서버에서 refresh token을 재발급하는 경우에만 발생하는 문제임.
현재는 reissue-token 요청시 accessToken만 재발급하므로 발생하지 않는 문제임. 즉, 오버엔지니어링...
<br><br>
* 문제 파악
https://roronoa-jongjin.tistory.com/3
* 참고했던 구현 방법
https://medium.com/@sina.alizadeh120/repeating-failed-requests-after-token-refresh-in-axios-interceptors-for-react-js-apps-50feb54ddcbc

Feat/#288 accesstoken 재발급 기능 구현

---

src/components/Place/PreviewContentSummary.tsx

#309 
<br><br>
아래 사진의 isMarked의 boolean은 쏠루트와 쏠마크에서 PreviewContentSummary를 사용할 때 사용되는 것이고,
쏠렉트에서 PreviewContentSummary를 사용할 때는 place.isMarked의 boolean을 사용해야하더라구요. 
<br><br>
<br><br>
<br><br>

[fix/#309] SolmarkChip의 props로 place.isMarked 전달

---

src/components/Sollect/SollectDetail/AddCourseButton.tsx

장소로 저장 클릭시 쏠루트로 이동할 수 있는 모달을 띄운다.
#308 
<br><br>
- 장소로 저장 클릭시 모달로 저장 완료 여부를 알려줌
- 쏠루트로 이동해 저장된 쏠루트를 확인할 수 있음
- 쏠렉트를 이어서 볼 수 있음
<br><br>
<br><br>
<br><br>

[feat/#308] 장소로 저장 기획 변경 반영

---

src/auth/OAuthCallback.tsx

withCredentials: true가 없다면 쿠키의 도메인이 다를 경우 set-cookie 를 무시함
#318 
<br><br>
third-party 쿠키를 저장하기 위해 
api 요청 header에 `withCredentials: true`를 추가함
해당 값이 없다면 쿠키가 넘어와도 브라우저에서 쿠키를 저장하지 않음
<br><br>
<br><br>
<br><br>
https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials

[fix/#318] accessToken 요청 api에 withCredentials: true 설정 추가

---

src/components/Searching/SearchArea.tsx

#326 
<br><br>
기존 아이콘 버튼에서 ‘완료’ 및 ‘닫기’ 버튼 제공으로 사용자 액션 명확화
<br><br>
<br><br>
<br><br>

[faet/#326] ‘완료’ 및 ‘닫기’ 버튼 제공으로 사용자 액션 명확화

---

src/components/BottomSheet/DetailContent.tsx
src/components/Sollect/SollectDetail/AddCourseButton.tsx
src/components/Sollect/SollectDetail/SollectDetailHeader.tsx
src/components/Sollect/SollectPhoto.tsx
src/components/global/Loading.tsx
src/index.css
src/layout/SollectWriteLayout.tsx
src/pages/ReviewWritePage.tsx
src/pages/SollectDetailPage.tsx
src/pages/SollectWritePage.tsx
src/pages/profile/AddPlacePage.tsx
src/pages/profile/FeedbackPage.tsx
src/pages/solroute/SolrouteDetailPage.tsx
src/pages/solroute/SolrouteWritePage.tsx
src/routes/AppRouter.tsx

#330 
<br><br>
* Loading 컴포넌트 생성
* delay가 있어 버튼 클릭 후 바로 Loading 컴포넌트를 호출지 않도록 함
* 생성 및 조회 등 api 호출시 delay가 있을 확률이 높은 곳에 Loading 컴포넌트 추가
* 쏠렉트 수정 데이터 fetch 리팩토링 
* 기존에는 수정 버튼에서 데이터를 가져왔음
* 이에 변환 함수 호출을 각 버튼마다 실행해야하는 문제 존재
* 쏠렉트 작성 page에서 기존 쏠렉트의 데이터를 fetch하도록 변경해 문제 해결
<br><br>
<br><br>
Loading 컴포넌트 사용법
```javascript
{<Loading active={isPending} text='쏠렉트 불러오는 중' delayMs={100} />}
```
* `active : boolean` : 사용자가 요청한 것의 상태를 나타내는 값. 요청 완료시 상태가 변해야 함 ex) `isPending` 
* `text : string` : 로딩 화면에 나타낼 문자. 뒤에 자동으로 `...`을 추가함
* `delayMs? : number` : 요청 후 몇 ms 뒤에 Loading 컴포넌트가 나타날지 정하는 값
<br><br>
https://www.nngroup.com/articles/response-times-3-important-limits/

Feat/#330 sollect 등록시 spinner 추가

---

src/components/Solroute/SolrouteTitle.tsx
src/pages/solroute/SolrouteWritePage.tsx

#337 
<br><br>
이 pull request는 솔루트(Solroute) 작성 UI의 소소한 개선사항을 담고 있습니다. 명확성을 위해 자리 표시자(placeholder)와 토스트(toast) 메시지를 업데이트했습니다.
---
- `SolrouteTitle` 입력창의 자리 표시자 텍스트를 "코스명을 입력해주세요"에서 **"제목을 입력해주세요"로 변경**하여 일관성과 명확성을 높였습니다.
- 제목이 없을 때 표시되는 토스트 경고 메시지를 **"제목을 입력해주세요."로 변경**하여 사용자에게 더 정확한 안내를 제공합니다.
<br><br>
<br><br>
<br><br>

[chore/#337] '코스명' 텍스트를 '제목'으로 변경

---

src/components/Solroute/SolrouteMap.tsx
src/pages/solroute/SolrouteDetailPage.tsx

#341 
<br><br>
이 pull request는 `SolrouteDetailPage`에 드래그 가능한 분할 뷰를 도입하여 사용자가 지도와 장소 정보 섹션의 크기를 **대화형으로 조절**할 수 있게 합니다. 주요 변경 사항은 새로운 드래그 앤 드롭 로직, 지도의 동적 높이 관리, 그리고 더 나은 반응성을 위한 `SolrouteMap` 컴포넌트의 관련 업데이트를 포함합니다.
---
- 사용자가 분할선(divider)을 드래그하여 지도 섹션의 높이를 조절할 수 있도록 **마우스 및 터치 이벤트 핸들러**를 구현했습니다. 이 기능은 최소/최대 높이 제약 조건을 포함하며, 드래그 중 커서 및 선택 스타일을 업데이트하여 부드러운 사용자 경험을 보장합니다.
- 분할 뷰 및 드래그 동작을 관리하기 위해 **`topHeight`, `isDragging`와 같은 상태 변수와 `containerRef`와 같은 참조(refs)를 추가**했습니다.
- 지도와 장소 정보 컨테이너가 있는 **플렉스 컬럼(flex column) 레이아웃을 사용**하도록 업데이트했습니다. 지도의 높이는 `topHeight`에 의해 동적으로 설정되고, 정보 컨테이너는 남은 공간을 채우게 됩니다.
---
- `SolrouteMap` 컴포넌트가 **새로운 `mapHeight` prop을 받도록 수정**하고, 높이가 변경될 때마다 지도 인스턴스에 지연된 `autoResize`를 트리거하도록 했습니다. 이를 통해 사용자가 분할선을 드래그할 때 지도가 올바르게 크기를 조절하도록 보장합니다.
- 언마운트 시 오래된 참조를 방지하기 위해 …

[feat/#341] 쏠루트 조회 화면 지도 크기를 스크롤 상황에 따라 조정

---

src/pages/solroute/SolrouteDetailPage.tsx

#345 
<br><br>
이 pull request는 SolrouteDetailPage 컴포넌트의 컨테이너에 사소한 UI 변경을 적용합니다. onMouseDown과 onTouchStart 이벤트 핸들러를 외부 컨테이너에서 내부 컨테이너로 이동했습니다. 이 변경은 사용자 상호작용이 UI에서 처리되는 방식에 영향을 줄 수 있습니다.
<br><br>
<br><br>
<br><br>

[fix/#345] 장소 정보 컨테이너의 이벤트 핸들러 위치 변경
